-- Triage apply: bind unsure photos and insert new items

-- 1. Insert new items implied by unmatched photos
INSERT INTO menu_items (subsection_id, slug, name, description, is_available, available_at, notes) VALUES (24, 'bubble-waffle', $$Bubble Waffle$$, $$Hong Kong-style bubble waffle.$$, true, ARRAY['newry']::TEXT[], 'Added 2026-05-26 from unmatched photo triage') ON CONFLICT (slug) DO NOTHING;
INSERT INTO menu_items (subsection_id, slug, name, description, is_available, available_at, notes) VALUES (10, 'mixed-grain-energy-bowl', $$Mixed Grain Energy Bowl$$, $$Hearty grain bowl for a wholesome start.$$, true, ARRAY['newry']::TEXT[], 'Added 2026-05-26 from unmatched photo triage') ON CONFLICT (slug) DO NOTHING;
INSERT INTO menu_items (subsection_id, slug, name, description, is_available, available_at, notes) VALUES (10, 'english-muffin', $$English Muffin$$, $$Classic toasted English muffin.$$, true, ARRAY['newry']::TEXT[], 'Added 2026-05-26 from unmatched photo triage') ON CONFLICT (slug) DO NOTHING;
INSERT INTO menu_items (subsection_id, slug, name, description, is_available, available_at, notes) SELECT ss.id, 'dubai-chocolate-bingsu', $$Dubai Chocolate Bingsu$$, $$Dubai chocolate flavour shaved-ice dessert.$$, true, ARRAY['newry']::TEXT[], 'Added 2026-05-26 from unmatched photo triage' FROM subsections ss JOIN sections s ON ss.section_id = s.id WHERE s.slug = 'bingsu' ORDER BY ss.id LIMIT 1 ON CONFLICT (slug) DO NOTHING;
INSERT INTO menu_items (subsection_id, slug, name, description, is_available, available_at, notes) SELECT ss.id, 'biscoff-rocky-road', $$Biscoff Rocky Road$$, $$Rocky road with Biscoff (Lotus) crumble.$$, true, ARRAY['newry']::TEXT[], 'Added 2026-05-26 from unmatched photo triage' FROM subsections ss JOIN sections s ON ss.section_id = s.id WHERE s.slug = 'cakes-cookies-bites' ORDER BY ss.id LIMIT 1 ON CONFLICT (slug) DO NOTHING;
INSERT INTO menu_items (subsection_id, slug, name, description, is_available, available_at, notes) SELECT ss.id, 'pizza-quesadilla', $$Pizza Quesadilla$$, $$Pizza-style quesadilla.$$, true, ARRAY['newry']::TEXT[], 'Added 2026-05-26 from unmatched photo triage' FROM subsections ss JOIN sections s ON ss.section_id = s.id WHERE s.slug = 'lunch' ORDER BY ss.id LIMIT 1 ON CONFLICT (slug) DO NOTHING;

-- 2. Bind photos to items (existing + newly inserted)
UPDATE menu_items SET image_url = '/menu-photos/golden-toast/ChocoBananaGT.webp' WHERE name = $$Choco Banana Golden Toast$$;
UPDATE menu_items SET image_url = '/menu-photos/golden-toast/MangoGT.webp' WHERE name = $$Mango Golden Toast$$;
UPDATE menu_items SET image_url = '/menu-photos/golden-toast/MixedBerryGT.webp' WHERE name = $$Mixed Berry Golden Toast$$;
UPDATE menu_items SET image_url = '/menu-photos/golden-toast/ApplePieGT.webp' WHERE name = $$Apple Pie Golden Toast$$;
UPDATE menu_items SET image_url = '/menu-photos/keto-vegan-gluten-free/Belgian-Waffle.jpg' WHERE name = $$Almond Belgium Waffle (K)$$;
UPDATE menu_items SET image_url = '/menu-photos/pancakes-waffles/Bubble-Waffle.jpg' WHERE name = $$Bubble Waffle$$;
UPDATE menu_items SET image_url = '/menu-photos/bingsu/CarmelApplePie.webp' WHERE name = $$Caramel Apple Bingsu$$;
UPDATE menu_items SET image_url = '/menu-photos/bingsu/BiscoffBananaBingsu.webp' WHERE name = $$Lotus Banana Bingsu$$;
UPDATE menu_items SET image_url = '/menu-photos/bingsu/DubaiChocolateBingsu.webp' WHERE name = $$Dubai Chocolate Bingsu$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/AppleFruitTea.webp' WHERE name = $$Apple Jasmine Green Tea$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/RaspberryFruitTea.webp' WHERE name = $$Raspberry Jasmine Green Tea$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/KumquatFruitTea.webp' WHERE name = $$Kumquat Jasmine Green Tea$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/PassionfruitFruitTea.webp' WHERE name = $$Passionfruit Assam Black Tea$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/LemonFruitTea.webp' WHERE name = $$Lemon Assam Black Tea$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/MangoFruitTea.webp' WHERE name = $$Mango Jasmine Green Tea$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/LycheeFruitTea.webp' WHERE name = $$Lychee Jasmine Green Tea$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/RaspberryFruitTea.webp' WHERE name = $$Raspberry Jasmine Green Tea$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Frappe.jpg' WHERE name = $$Bounty Frappe$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Frappe.jpg' WHERE name = $$Chocolate Chip Frappe$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Frappe.jpg' WHERE name = $$Kinder Bueno Frappe$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Frappe.jpg' WHERE name = $$Lotus Biscoff Frappe$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Frappe.jpg' WHERE name = $$Pistachio Frappe$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Frappe.jpg' WHERE name = $$Strawberry Cheesecake Frappe$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Frappe.jpg' WHERE name = $$Summer Fruits Frappe$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Acai Kick Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Beet & Berry Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Berry Burst Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Coconut Crush Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Green Reviver Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Mango Dream Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Oaty Banana Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Passion Storm Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Pineapple Sunset Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Raspberry Heaven Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/signature-drinks/Smoothie.jpg' WHERE name = $$Strawberry Fantasy Smoothie$$;
UPDATE menu_items SET image_url = '/menu-photos/cakes-cookies-bites/Biscoff-Rocky-Road.jpg' WHERE name = $$Biscoff Rocky Road$$;
UPDATE menu_items SET image_url = '/menu-photos/cakes-cookies-bites/Caramel-Square.jpeg' WHERE name = $$Belgium Caramel Square$$;
UPDATE menu_items SET image_url = '/menu-photos/keto-vegan-gluten-free/Snickers-Cake-GF-.jpeg' WHERE name = $$Snickers Cake / Toblerone (GF)$$;
UPDATE menu_items SET image_url = '/menu-photos/keto-vegan-gluten-free/Vegan-Toastie.png' WHERE name = $$Toastie/Sandwich (GF)$$;
UPDATE menu_items SET image_url = '/menu-photos/keto-vegan-gluten-free/Vegan-Sandwich.png' WHERE name = $$Toastie/Sandwich (GF)$$;
UPDATE menu_items SET image_url = '/menu-photos/keto-vegan-gluten-free/Snickers-Cake.jpeg' WHERE name = $$Snickers Cake / Toblerone (GF)$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Omelette-Tortilla.jpeg' WHERE name = $$Tortilla Omelette$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Pizza-Bagel.jpg' WHERE name = $$Sourdough Pizza Bagel$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Bagel.jpg' WHERE name = $$Sourdough Bagel$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Bagel.jpg' WHERE name = $$Sourdough Pizza Bagel$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Pasta.jpg' WHERE name = $$Pasta Tagliatelle$$;
UPDATE menu_items SET image_url = '/menu-photos/pancakes-waffles/Crepe-Savory-.jpg' WHERE name = $$Crepe$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Pizza-Quesedilla.jpeg' WHERE name = $$Pizza Quesadilla$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Goujons.png' WHERE name = $$Chicken Goujons x3$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Goujons-Fries.png' WHERE name = $$Goujons & Chips$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Fries.png' WHERE name = $$Chips$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Soup.jpeg' WHERE name = $$Homemade Soup of the Day$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Pizza-Quesedilla.jpeg' WHERE name = $$Pizza Quesadilla$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Black-Jack-Burger.jpeg' WHERE name = $$Black Jack Pulled Pork Burger$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Ramen.jpeg' WHERE name = $$Ramen Soup (*V)$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Meatball-Pasta.jpg' WHERE name = $$Meatball Tagliatelle Pasta$$;
UPDATE menu_items SET image_url = '/menu-photos/breakfast-brunch/French-Toast.png' WHERE name = $$French Toast x2 with Bacon & Maple Syrup$$;
UPDATE menu_items SET image_url = '/menu-photos/keto-vegan-gluten-free/Almond-Belgian-Waffle.jpeg' WHERE name = $$Almond Belgium Waffle (K)$$;
UPDATE menu_items SET image_url = '/menu-photos/keto-vegan-gluten-free/Mozzarella-Omelette-Sandwich.jpeg' WHERE name = $$Mozzarella Omelette Sandwich (K)$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Omelette-Tortilla.jpeg' WHERE name = $$Tortilla Omelette$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/Mixed-Grain-Energy-Bowl.jpg' WHERE name = $$Mixed Grain Energy Bowl$$;
UPDATE menu_items SET image_url = '/menu-photos/lunch/English-Muffin.jpg' WHERE name = $$English Muffin$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Croissant.jpg' WHERE name = $$Butter & Jam Croissant$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Croissant.jpg' WHERE name = $$Ham & Cheese Croissant$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Croissant.jpg' WHERE name = $$Lemon Croissant$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Croissant.jpg' WHERE name = $$Nutella Croissant$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Croissant.jpg' WHERE name = $$Pistachio Croissant$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Croissant.jpg' WHERE name = $$Plain Croissant$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Scone.jpg' WHERE name = $$Fruit Scone$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Scone.jpg' WHERE name = $$Gluten Free Scone$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Scone.jpg' WHERE name = $$Plain Scone$$;
UPDATE menu_items SET image_url = '/menu-photos/bakery-pastries/Scone.jpg' WHERE name = $$Raspberry & White Chocolate Scone$$;
UPDATE menu_items SET image_url = '/menu-photos/coffee-tea/Mocha.jpg' WHERE name = $$Mocha / White Mocha$$;