-- Item allergens
INSERT INTO public.item_allergens (menu_item_id, allergen_code) VALUES
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'souffle-pancake' AND mi.slug = 's-more-souffle-pancake'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'american-pancake' AND mi.slug = 'original-american-pancake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'american-pancake' AND mi.slug = 'original-american-pancake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'american-pancake' AND mi.slug = 'original-american-pancake'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'american-pancake' AND mi.slug = 'matcha-american-pancake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'american-pancake' AND mi.slug = 'matcha-american-pancake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'american-pancake' AND mi.slug = 'matcha-american-pancake'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'strawberry-waffle'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'strawberry-waffle'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'strawberry-waffle'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'oreo-waffle'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'oreo-waffle'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'oreo-waffle'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'oreo-waffle'), 'N'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'strawberry-choco-waffle'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'strawberry-choco-waffle'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'strawberry-choco-waffle'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'strawberry-choco-waffle'), 'N'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'banana-lotus-waffle'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'banana-lotus-waffle'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'banana-lotus-waffle'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'plain-waffle-with-nutella-ice-cream'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'plain-waffle-with-nutella-ice-cream'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'plain-waffle-with-nutella-ice-cream'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'plain-waffle-with-nutella-ice-cream'), 'N'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'lemon-maple-syrup-icing-waffle'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'lemon-maple-syrup-icing-waffle'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'pancakes-waffles' AND s.slug = 'waffle' AND mi.slug = 'lemon-maple-syrup-icing-waffle'), 'Eg'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'blueberry-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'taro-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'thai-tea-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'matcha-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'strawberry-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'caramel-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'assam-black-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'dark-oolong-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'chocolate-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'brown-sugar-milk-tea'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'strawberry-cheesecake-frappe'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'strawberry-cheesecake-frappe'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'kinder-bueno-frappe'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'kinder-bueno-frappe'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'lotus-biscoff-frappe'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'lotus-biscoff-frappe'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'bounty-frappe'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'bounty-frappe'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'chocolate-chip-frappe'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'chocolate-chip-frappe'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'summer-fruits-frappe'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'summer-fruits-frappe'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'pistachio-frappe'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'frappes' AND mi.slug = 'pistachio-frappe'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'taro-milkshake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'taro-milkshake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'mango-yogurt-milkshake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'mango-yogurt-milkshake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'oreo-vanilla-milkshake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'oreo-vanilla-milkshake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'vanilla-milkshake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'vanilla-milkshake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'pure-matcha-milkshake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'pure-matcha-milkshake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'banana-milkshake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'banana-milkshake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'strawberry-yogurt-milkshake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'strawberry-yogurt-milkshake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'caramel-milkshake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milkshakes' AND mi.slug = 'caramel-milkshake'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'protein-shakes' AND mi.slug = 'vanilla-protein-shake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'protein-shakes' AND mi.slug = 'chocolate-protein-shake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'protein-shakes' AND mi.slug = 'strawberry-protein-shake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'protein-shakes' AND mi.slug = 'banana-protein-shake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'protein-shakes' AND mi.slug = 'salted-caramel-protein-shake'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'coconut-kiss-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'coconut-kiss-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'tiramisu-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'tiramisu-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'beetroot-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'beetroot-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'strawberry-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'strawberry-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'banana-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'banana-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'creme-brulee-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'creme-brulee-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'blue-lagoon-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'blue-lagoon-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'ice-cream-espresso'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'ice-cream-espresso'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'lotus-biscoff-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'lotus-biscoff-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'peanut-butter-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'peanut-butter-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'kinder-bueno-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'kinder-bueno-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'cream-panner'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'cream-panner'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'coconut-coffee-lychee-blend'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'coconut-coffee-lychee-blend'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'creamy-coconut-coffee-dream'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'creamy-coconut-coffee-dream'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'pistachio-latte'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'pistachio-latte'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'panda'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'lattes-coffee-blends' AND mi.slug = 'panda'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'hot-chocolates' AND mi.slug = 'hot-chocolate'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'hot-chocolates' AND mi.slug = 'hot-chocolate'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'hot-chocolates' AND mi.slug = 'white-hot-chocolate'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'hot-chocolates' AND mi.slug = 'white-hot-chocolate'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'hot-chocolates' AND mi.slug = 'strawberry-hot-chocolate'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'hot-chocolates' AND mi.slug = 'strawberry-hot-chocolate'), 'G'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'hot-chocolates' AND mi.slug = 'baby-hot-chocolate'), 'M'),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'gourmet-lattes' AND s.slug = 'hot-chocolates' AND mi.slug = 'baby-hot-chocolate'), 'G');

-- Modifier groups: item-scoped
-- (also includes global modifier groups)
INSERT INTO public.modifier_groups (name, scope, scope_label, notes, display_order) VALUES
  ('Flavoured', 'item', 'ITEM::coffee-tea::matcha::matcha-latte::flavoured', NULL, 1),
  ('Extra Egg', 'item', 'ITEM::breakfast-brunch::breakfast-brunch::egg-toast::extra-egg', NULL, 1),
  ('Extra Egg', 'item', 'ITEM::breakfast-brunch::breakfast-brunch::hello-sunrise::extra-egg', NULL, 1),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::blueberry-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::blueberry-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::taro-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::taro-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::thai-tea-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::thai-tea-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::matcha-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::matcha-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::strawberry-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::strawberry-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::caramel-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::caramel-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::assam-black-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::assam-black-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::dark-oolong-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::dark-oolong-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::chocolate-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::chocolate-milk-tea::add-boba', NULL, 2),
  ('Hot', 'item', 'ITEM::signature-drinks::milk-tea::brown-sugar-milk-tea::hot', NULL, 1),
  ('Add Boba', 'item', 'ITEM::signature-drinks::milk-tea::brown-sugar-milk-tea::add-boba', NULL, 2),
  ('Decaf', 'global', 'GLOBAL::extras::decaf', 'Decaf Coffee / Tea', 1),
  ('Change Milk', 'global', 'GLOBAL::extras::change-milk', 'Choose from Soya, Oat, Coconut, Almond, Semi-Skimmed (Free)', 2),
  ('Add Syrup', 'global', 'GLOBAL::extras::add-syrup', 'Hazelnut, Vanilla, Caramel, Salted Caramel, Chocolate, Caramelized Peanut, Blueberry, Strawberry, Cherry, Cinnamon, Pumpkin Spiced, Irish Cream, Pistachio. Sugar Free: Caramel, Hazelnut, Vanilla.', 3),
  ('Iced Coffee', 'global', 'GLOBAL::coffee::iced-coffee', 'Available on any coffee or gourmet latte', 4),
  ('Gluten-Free Bread/Base Swap', 'global', 'GLOBAL::create-your-own-base-upgrades::gluten-free-bread-base-swap', 'Items containing bread, bagels, baps or waffles', 5),
  ('Sourdough Base Swap', 'global', 'GLOBAL::create-your-own-base-upgrades::sourdough-base-swap', 'Items containing bread, bagels, baps or waffles', 6),
  ('Pistachio Powder', 'global', 'GLOBAL::soft-serve-toppings::pistachio-powder', NULL, 7),
  ('Roasted Almonds', 'global', 'GLOBAL::soft-serve-toppings::roasted-almonds', NULL, 8),
  ('Oreo Crumbs', 'global', 'GLOBAL::soft-serve-toppings::oreo-crumbs', NULL, 9),
  ('Kit Kat Crumbs', 'global', 'GLOBAL::soft-serve-toppings::kit-kat-crumbs', 'Price listed as ''0.30'' without £ symbol in source', 10),
  ('Biscoff Lotus', 'global', 'GLOBAL::soft-serve-toppings::biscoff-lotus', NULL, 11),
  ('Coconut Flakes', 'global', 'GLOBAL::soft-serve-toppings::coconut-flakes', NULL, 12),
  ('Granola', 'global', 'GLOBAL::soft-serve-toppings::granola', NULL, 13),
  ('Marshmallows', 'global', 'GLOBAL::soft-serve-toppings::marshmallows', NULL, 14),
  ('Rainbow Sprinkles', 'global', 'GLOBAL::soft-serve-toppings::rainbow-sprinkles', NULL, 15),
  ('Chocolate Sprinkles', 'global', 'GLOBAL::soft-serve-toppings::chocolate-sprinkles', NULL, 16),
  ('Flake', 'global', 'GLOBAL::soft-serve-toppings::flake', NULL, 17),
  ('Strawberry Sauce', 'global', 'GLOBAL::soft-serve-sauces::strawberry-sauce', 'Free', 18),
  ('Pistachio Sauce', 'global', 'GLOBAL::soft-serve-sauces::pistachio-sauce', 'Free', 19),
  ('Mango Sauce', 'global', 'GLOBAL::soft-serve-sauces::mango-sauce', 'Free', 20),
  ('Bueno Sauce', 'global', 'GLOBAL::soft-serve-sauces::bueno-sauce', 'Free', 21),
  ('Passionfruit Sauce', 'global', 'GLOBAL::soft-serve-sauces::passionfruit-sauce', 'Free', 22),
  ('Bubblegum Sauce', 'global', 'GLOBAL::soft-serve-sauces::bubblegum-sauce', 'Free', 23),
  ('Chocolate Sauce', 'global', 'GLOBAL::soft-serve-sauces::chocolate-sauce', 'Free', 24),
  ('White Chocolate Sauce', 'global', 'GLOBAL::soft-serve-sauces::white-chocolate-sauce', 'Free', 25),
  ('Oreo Sauce', 'global', 'GLOBAL::soft-serve-sauces::oreo-sauce', 'Free', 26),
  ('Caramel Sauce', 'global', 'GLOBAL::soft-serve-sauces::caramel-sauce', 'Free', 27);

-- Modifier options
INSERT INTO public.modifier_options (modifier_group_id, name, price_delta) VALUES
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::coffee-tea::matcha::matcha-latte::flavoured'), 'Strawberry Matcha', 0.5),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::coffee-tea::matcha::matcha-latte::flavoured'), 'Blueberry Matcha', 0.5),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::coffee-tea::matcha::matcha-latte::flavoured'), 'Cherry Matcha', 0.5),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::coffee-tea::matcha::matcha-latte::flavoured'), 'Coconut Matcha', 0.5),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::breakfast-brunch::breakfast-brunch::egg-toast::extra-egg'), 'Extra Egg', 0.6),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::breakfast-brunch::breakfast-brunch::hello-sunrise::extra-egg'), 'Extra Egg', 0.6),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::blueberry-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::blueberry-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::blueberry-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::blueberry-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::taro-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::taro-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::taro-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::taro-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::thai-tea-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::thai-tea-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::thai-tea-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::thai-tea-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::matcha-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::matcha-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::matcha-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::matcha-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::strawberry-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::strawberry-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::strawberry-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::strawberry-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::caramel-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::caramel-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::caramel-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::caramel-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::assam-black-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::assam-black-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::assam-black-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::assam-black-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::dark-oolong-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::dark-oolong-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::dark-oolong-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::dark-oolong-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::chocolate-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::chocolate-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::chocolate-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::chocolate-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::brown-sugar-milk-tea::hot'), 'Hot', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::brown-sugar-milk-tea::add-boba'), 'Tapioca', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::brown-sugar-milk-tea::add-boba'), 'Popping Boba', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::brown-sugar-milk-tea::add-boba'), 'Rainbow Jelly', 1.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::extras::decaf'), 'Decaf', 0.3),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::extras::change-milk'), 'Change Milk', 0.5),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::extras::add-syrup'), 'Add Syrup', 0.5),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::coffee::iced-coffee'), 'Iced Coffee', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::create-your-own-base-upgrades::gluten-free-bread-base-swap'), 'Gluten-Free Bread/Base Swap', 0.7),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::create-your-own-base-upgrades::sourdough-base-swap'), 'Sourdough Base Swap', 0.5),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::pistachio-powder'), 'Pistachio Powder', 0.5),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::roasted-almonds'), 'Roasted Almonds', 0.4),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::oreo-crumbs'), 'Oreo Crumbs', 0.3),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::kit-kat-crumbs'), 'Kit Kat Crumbs', 0.3),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::biscoff-lotus'), 'Biscoff Lotus', 0.3),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::coconut-flakes'), 'Coconut Flakes', 0.3),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::granola'), 'Granola', 0.3),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::marshmallows'), 'Marshmallows', 0.3),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::rainbow-sprinkles'), 'Rainbow Sprinkles', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::chocolate-sprinkles'), 'Chocolate Sprinkles', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-toppings::flake'), 'Flake', 0.2),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::strawberry-sauce'), 'Strawberry Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::pistachio-sauce'), 'Pistachio Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::mango-sauce'), 'Mango Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::bueno-sauce'), 'Bueno Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::passionfruit-sauce'), 'Passionfruit Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::bubblegum-sauce'), 'Bubblegum Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::chocolate-sauce'), 'Chocolate Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::white-chocolate-sauce'), 'White Chocolate Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::oreo-sauce'), 'Oreo Sauce', 0.0),
  ((SELECT id FROM public.modifier_groups WHERE scope_label = 'GLOBAL::soft-serve-sauces::caramel-sauce'), 'Caramel Sauce', 0.0);

-- Item ↔ modifier-group links (item-scoped)
INSERT INTO public.item_modifier_groups (menu_item_id, modifier_group_id) VALUES
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'coffee-tea' AND s.slug = 'matcha' AND mi.slug = 'matcha-latte'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::coffee-tea::matcha::matcha-latte::flavoured')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'breakfast-brunch' AND s.slug = 'breakfast-brunch' AND mi.slug = 'egg-toast'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::breakfast-brunch::breakfast-brunch::egg-toast::extra-egg')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'breakfast-brunch' AND s.slug = 'breakfast-brunch' AND mi.slug = 'hello-sunrise'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::breakfast-brunch::breakfast-brunch::hello-sunrise::extra-egg')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'blueberry-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::blueberry-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'blueberry-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::blueberry-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'taro-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::taro-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'taro-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::taro-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'thai-tea-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::thai-tea-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'thai-tea-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::thai-tea-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'matcha-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::matcha-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'matcha-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::matcha-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'strawberry-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::strawberry-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'strawberry-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::strawberry-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'caramel-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::caramel-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'caramel-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::caramel-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'assam-black-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::assam-black-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'assam-black-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::assam-black-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'dark-oolong-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::dark-oolong-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'dark-oolong-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::dark-oolong-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'chocolate-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::chocolate-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'chocolate-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::chocolate-milk-tea::add-boba')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'brown-sugar-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::brown-sugar-milk-tea::hot')),
  ((SELECT mi.id FROM public.menu_items mi JOIN public.subsections s ON s.id = mi.subsection_id JOIN public.sections sec ON sec.id = s.section_id WHERE sec.slug = 'signature-drinks' AND s.slug = 'milk-tea' AND mi.slug = 'brown-sugar-milk-tea'), (SELECT id FROM public.modifier_groups WHERE scope_label = 'ITEM::signature-drinks::milk-tea::brown-sugar-milk-tea::add-boba'));
