-- Revolut sync: new items + sushi prices + 1:1 id linking (idempotent)

-- 12 new items from Revolut
INSERT INTO public.menu_items (subsection_id, slug, name, price, display_order, needs_review, revolut_product_id, tags, notes) VALUES
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='bakery-pastries' AND s.slug='other-pastries'), 'beef-mince-pie', 'Beef & Mince Pie', 5.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='bakery-pastries' AND s2.slug='other-pastries'), TRUE, 'Beef&mince pie', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='bakery-pastries' AND s.slug='croissants'), 'lemon-croissant', 'Lemon Croissant', 3.6, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='bakery-pastries' AND s2.slug='croissants'), TRUE, 'Lemon Croissant', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='bakery-pastries' AND s.slug='other-pastries'), 'pistachio-donut', 'Pistachio Donut', 3.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='bakery-pastries' AND s2.slug='other-pastries'), TRUE, 'Pistachio donut', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='breakfast-brunch' AND s.slug='breakfast-brunch'), 'side-of-bacon', 'Side of Bacon', 1.5, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='breakfast-brunch' AND s2.slug='breakfast-brunch'), TRUE, 'Side of bacon', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='breakfast-brunch' AND s.slug='breakfast-brunch'), 'smoothie-bowl', 'Smoothie Bowl', 8.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='breakfast-brunch' AND s2.slug='breakfast-brunch'), TRUE, 'Smoothie Bowl', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='cakes-cookies-bites' AND s.slug='cakes-pies'), 'banana-bread', 'Banana Bread', 5.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='cakes-cookies-bites' AND s2.slug='cakes-pies'), TRUE, 'Banana Bread', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='cakes-cookies-bites' AND s.slug='cakes-pies'), 'cookie-cake', 'Cookie Cake', 5.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='cakes-cookies-bites' AND s2.slug='cakes-pies'), TRUE, 'Cookie Cake', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='coffee-tea' AND s.slug='matcha'), 'creamy-matcha', 'Creamy Matcha', 5.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='coffee-tea' AND s2.slug='matcha'), TRUE, 'Creamy Matcha', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='keto-vegan-gluten-free' AND s.slug='keto'), 'creamy-almond-coffee-dream-k', 'Creamy Almond Coffee Dream (K)', 6.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='keto-vegan-gluten-free' AND s2.slug='keto'), TRUE, 'Creamy Almond Coffee Dream (K)', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='lunch' AND s.slug='mains'), 'beetroot-belgium-waffle', 'Beetroot Belgium Waffle', 12.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='lunch' AND s2.slug='mains'), TRUE, 'Beetroot Belgium Waffle', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='lunch' AND s.slug='create-your-own'), 'ciabatta', 'Ciabatta', 9.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='lunch' AND s2.slug='create-your-own'), TRUE, 'Ciabatta', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.'),
  ((SELECT s.id FROM public.subsections s JOIN public.sections sec ON sec.id=s.section_id WHERE sec.slug='lunch' AND s.slug='mains'), 'fried-rice', 'Fried Rice', 10.0, (SELECT COALESCE(MAX(mi2.display_order),0)+1 FROM public.menu_items mi2 JOIN public.subsections s2 ON s2.id=mi2.subsection_id JOIN public.sections sec2 ON sec2.id=s2.section_id WHERE sec2.slug='lunch' AND s2.slug='mains'), TRUE, 'fried rice', ARRAY['new']::text[], 'Added from Revolut export 2026-05-24; confirm name, description & allergens.')
ON CONFLICT (subsection_id, slug) DO NOTHING;

-- Sushi platter prices
UPDATE public.item_variants SET price=12.0 WHERE name='8-piece' AND menu_item_id=(SELECT id FROM public.menu_items WHERE slug='sushi-platter');
UPDATE public.item_variants SET price=24.0 WHERE name='16-piece' AND menu_item_id=(SELECT id FROM public.menu_items WHERE slug='sushi-platter');
UPDATE public.item_variants SET price=30.0 WHERE name='20-piece' AND menu_item_id=(SELECT id FROM public.menu_items WHERE slug='sushi-platter');
UPDATE public.item_variants SET price=40.0 WHERE name='30-piece' AND menu_item_id=(SELECT id FROM public.menu_items WHERE slug='sushi-platter');
UPDATE public.item_variants SET price=70.0 WHERE name='50-piece' AND menu_item_id=(SELECT id FROM public.menu_items WHERE slug='sushi-platter');

-- Link revolut_product_id only on UNAMBIGUOUS 1:1 name matches
WITH rev(name) AS (VALUES
  ('16 pcs'),
  ('1x Egg & 2x Toasted bread With Butter'),
  ('1x slice toast with 1x egg'),
  ('1x sliced toast with Scramble eggs'),
  ('2 sausages n toast'),
  ('20 pcs'),
  ('30 pcs'),
  ('50 pcs'),
  ('8pc'),
  ('Acai Granola Bowl'),
  ('Acai coconut 🥥'),
  ('Add Syrup'),
  ('Add Toppings'),
  ('Air Fried Sushi Hot Dog'),
  ('Almond Belgium Waffle (K)(GF)'),
  ('Amaretto cake'),
  ('American Pancakes'),
  ('Americano'),
  ('Apple / Orange Juice'),
  ('Baby'),
  ('Babyccino'),
  ('Bag'),
  ('Bagel'),
  ('Bagel (GF) (V)'),
  ('Bagel W/ Poached Egg & Bacon'),
  ('Balsamic Mozzarella Salad'),
  ('Banana Bread'),
  ('Banana Latte'),
  ('Bap'),
  ('Bap (GF)'),
  ('Beef&mince pie'),
  ('Beetroot Belgium Waffle'),
  ('Beetroot Latte (Decaf)'),
  ('Beetroot-Feta Burger'),
  ('Belgian Waffle'),
  ('Belgium Caramel squares'),
  ('Bibimbap'),
  ('Bingsu'),
  ('Biscoff Rocky Road'),
  ('Black Forest Gateaux'),
  ('Black Jack Pulled Pork Burger Bun'),
  ('Blue Lagoon Latte'),
  ('Breakfast Mffin'),
  ('Breakfast Omelette Taco'),
  ('Brie Mine Croissant'),
  ('Brownie'),
  ('Bubble Waffle'),
  ('Burning Love Burger'),
  ('Burrata/Mozzarella & Mango Salad'),
  ('Caesar Salad'),
  ('Cappuccino'),
  ('Caprese Salad'),
  ('Capri Sun Small'),
  ('Caramel Apple Muffin'),
  ('Carrot Cake'),
  ('Chai latte'),
  ('Change Milk'),
  ('Cherry Velvet Sip'),
  ('Chicken Curry'),
  ('Chicken Goujons x3'),
  ('Chips'),
  ('Chocolate Fudge Cake (GF)'),
  ('Chocolate cake'),
  ('Christmas toastie 🎅'),
  ('Ciabatta'),
  ('Cinnamon bun'),
  ('Coconut Coffee Lychee Blend'),
  ('Coconut Kiss Latte'),
  ('Coconut protein ball'),
  ('Coffee Beans'),
  ('Coffee Cake'),
  ('Coke'),
  ('Cookie'),
  ('Cookie Cake'),
  ('Cranberry Brie Toast'),
  ('Cream Panner'),
  ('Creamy Almond Coffee Dream (K)'),
  ('Creamy Coconut Coffee Dream'),
  ('Creamy Matcha'),
  ('Create Your Own Salad'),
  ('Creme Brûlée Latte'),
  ('Crepe (Savoury)'),
  ('Crepe (Sweet)'),
  ('Crisps'),
  ('Crispy Chicken Naan Kebab'),
  ('Crispy Chicken Salad'),
  ('Crisy&BBQ Wings'),
  ('Croissant'),
  ('Crumble Cookie'),
  ('Cupcake'),
  ('Cupid’s Cocoa'),
  ('Danish pastries'),
  ('Decaf'),
  ('Doughnut'),
  ('Dubai Chocolate'),
  ('Egg Toast'),
  ('Einspanner'),
  ('Espresso'),
  ('Extra 0.50'),
  ('Extra 0.60'),
  ('Extra 1.00'),
  ('Extra 2.00'),
  ('Extra Shot'),
  ('Fanta'),
  ('Festive Fries 🎅'),
  ('Festive Toastie'),
  ('Fishcake  Burger'),
  ('Flat White'),
  ('Frappé'),
  ('French Toast Benedict'),
  ('French Toast w/bacon and maple syrup'),
  ('French Toast x2'),
  ('Fruit Scone (GF)'),
  ('Fruit Shoots'),
  ('Fruit Tea'),
  ('Glass of Milk'),
  ('Gluten Free Blueberry Muffin'),
  ('Golden Toast'),
  ('Good Morning Breakfast'),
  ('Goujons & Fries'),
  ('Greek Salad'),
  ('Green Oasis'),
  ('Ham&cheese Taco'),
  ('Hello Sunrise'),
  ('Homemade Soup of the Day'),
  ('Honey Cake'),
  ('Hot Chocolate'),
  ('Ice-Cream Espresso'),
  ('Irish power energy drink'),
  ('Irish power water'),
  ('Jacket Potato'),
  ('Jasmine Brew Tea'),
  ('Jug of Dilute'),
  ('Kinder Bueno'),
  ('Kinder Bueno Latte'),
  ('Kombucha'),
  ('Latte'),
  ('Lemon Croissant'),
  ('Lemon Meringue'),
  ('Lemon Muffin'),
  ('Loose jasmine tea / whole pack'),
  ('Lotus Biscoff Latte'),
  ('Love Toast'),
  ('Lychee Mojito (Virgin)'),
  ('Macaroon (GF)'),
  ('Macaroons (GF)'),
  ('Macchiato'),
  ('Matcha Latte'),
  ('Matcha ice tea'),
  ('Matcha tea'),
  ('Meatball Pasta'),
  ('Merry Meerkat'),
  ('Mexican Panini'),
  ('Milk Tea'),
  ('Milkshake'),
  ('Mince pie'),
  ('Mocaccino'),
  ('Mocha'),
  ('Mohawk Burger'),
  ('Mozzarella Omelette Sandwich (K)(GF)'),
  ('Muffin'),
  ('Muffin (GF)'),
  ('Mulled Orange coffee 🎅'),
  ('Omelette (K)(GF)'),
  ('Omelette Tortilla Bake'),
  ('Oreo cake'),
  ('Outs pot'),
  ('Panda'),
  ('Panini'),
  ('Passion Fruit Mojito (Virgin)'),
  ('Passionfruit Cake'),
  ('Pasta'),
  ('Peanut Butter Latte'),
  ('Peanut Butter Snickers Cake'),
  ('Pink Matcha Latte'),
  ('Pistachio Latte'),
  ('Pistachio donut'),
  ('Pizza Bagel'),
  ('Poke bowl'),
  ('Porridge'),
  ('Portuguese Custard Tart'),
  ('Prosciutto Ham & Feta Cheese Baguette'),
  ('Protein Shake'),
  ('Protein balls'),
  ('Quesadillas'),
  ('Rainbow Cake'),
  ('Raisin pastry'),
  ('Ramen soup'),
  ('Raspberry, Ginger & Lemon Tea'),
  ('Red Bull'),
  ('Red Velvet'),
  ('Regular'),
  ('Rice'),
  ('Rice Crispy'),
  ('Rocky Road'),
  ('Salad'),
  ('Salmon Bruschetta for Two'),
  ('Salmon Sunrise'),
  ('Sandwich'),
  ('Sandwich (GF) (V)'),
  ('Sausage Roll'),
  ('Scone'),
  ('Scrambled Egg Ciabatta'),
  ('Side of bacon'),
  ('Side of salmon'),
  ('Simply Morning'),
  ('Small breakfast'),
  ('Smoothie'),
  ('Smoothie Bowl'),
  ('Snickers / Toblerone Cake (GF)'),
  ('Soft serve sit in'),
  ('Soufflé Pancake'),
  ('Sourdough Pizza'),
  ('Sparkling Water'),
  ('Sprite'),
  ('Still Water'),
  ('Strawberry Apple Pie'),
  ('Strawberry Choco Brownie'),
  ('Strawberry Latte (Decaf)'),
  ('Strawberry Mocha'),
  ('Sushi'),
  ('Sushi Bowl (GF) (K)'),
  ('Tablerone Gluten Free'),
  ('Taco'),
  ('Take away sandwich'),
  ('Tea'),
  ('Tiramisu'),
  ('Tiramisu Latte'),
  ('Tiramisu glass cake'),
  ('Toasted bread x1 slice'),
  ('Toasted bread x2 slices'),
  ('Toastie'),
  ('Toastie (GF) (V)'),
  ('Tortilla Omelette'),
  ('Twix'),
  ('Vegan Burger (GF) (V)'),
  ('Vegan Jaffa cake'),
  ('Vegan Kiev (GF) (V)'),
  ('Vegan Sausages (GF) (V)'),
  ('Vegan Taco (GF) (V)'),
  ('Vegan choco orange pudding'),
  ('Vegan sausage ex'),
  ('Vegetarian Breakfast Taco'),
  ('Vit-Hit'),
  ('Waffle (GF)'),
  ('Wrap'),
  ('Zesty Lemon Cake'),
  ('acai granola'),
  ('add boba'),
  ('add coffee'),
  ('add egg'),
  ('add ice-cream large'),
  ('add ice-cream small'),
  ('almond Belgian waffle'),
  ('almond belgium waffle'),
  ('american pancake'),
  ('baby hot chocolate'),
  ('bagel (GF)'),
  ('bagel poached egg & bacon'),
  ('banana / creme brulee / blue lagoon / ice cream espresso'),
  ('beetroot feta burger'),
  ('bingsu large'),
  ('bingsu medium'),
  ('bingsu small'),
  ('black jack burger'),
  ('breakfast muffin'),
  ('cake'),
  ('chocolate fudge cake'),
  ('coconut kiss / tiramisu / beetroot / strawberry'),
  ('coconut lychee / creamy coconut / pistachio / panda'),
  ('crepe'),
  ('croissant (butter/nutella)'),
  ('croissant ham & cheese'),
  ('croissant pistachio'),
  ('dubai chocolate large'),
  ('fishcake burger'),
  ('frappe'),
  ('french toast w/bacon & maple syrup'),
  ('fried rice'),
  ('goujons'),
  ('green oasis / cherry sip / mojito'),
  ('hot milk tea'),
  ('iced'),
  ('jasmine brew'),
  ('lotus / peanut / kinder / cream panner'),
  ('macaroons'),
  ('meatball pasta full'),
  ('meatball pasta half'),
  ('mochaccino'),
  ('mozzarella omelette sandwich'),
  ('omelette'),
  ('omelette tortilla'),
  ('quesadilla'),
  ('ramen'),
  ('rocky road / belgium square'),
  ('salmon sunrise 1/2'),
  ('salmon sunrise full'),
  ('sandwich / toastie (GF)'),
  ('scone (GF)'),
  ('scrambled egg ciabata'),
  ('smoothie toppings'),
  ('snickers cake'),
  ('snickers cake (GF)'),
  ('souffle pancake'),
  ('soup'),
  ('strawberry babycino'),
  ('sushi bowl'),
  ('tea pot'),
  ('toppings - almonds'),
  ('toppings - pistachio powder'),
  ('toppings - sprinkles/flake'),
  ('vegan burger'),
  ('vegan kiev'),
  ('vegan meat'),
  ('vegan sausage Bap'),
  ('vegan taco'),
  ('waffle / bubble waffle'),
  ('x2 toast x2 egg')
),
matched AS (
  SELECT mi.id, rev.name AS rev_name
  FROM public.menu_items mi
  JOIN rev ON lower(btrim(mi.name)) = lower(btrim(rev.name))
  WHERE mi.revolut_product_id IS NULL
),
solo AS (
  SELECT id, rev_name FROM matched
  WHERE rev_name IN (SELECT rev_name FROM matched GROUP BY rev_name HAVING count(*)=1)
    AND id     IN (SELECT id     FROM matched GROUP BY id     HAVING count(*)=1)
)
UPDATE public.menu_items mi SET revolut_product_id = solo.rev_name
FROM solo WHERE mi.id = solo.id;